blank_issues_enabled: true
contact_links:
  - name: Yukki Support
    url: https://t.me/ShadowsArena
    about: Direct chat on non-inquiries subjects.
  - name: Documentation
    url: https://t.me/ShadowKing9o
    about: Documentation for getting started with bot.
